id: IAFE2AE44
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T19:53:40.929324'
last_modified: '2022-06-05T19:53:40.929338'
parser: null
source_metadata:
  title: Seventh Dalai Lama Series
  language: en
  description: 'Texts by the Seventh Dalai Lama, Kalzang Gyatso (skal bzang rgya mtsho,
    1708–1757):'
  volume:
    f1001:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      base_file: f1001.txt
      order: 1
      parent: Songs
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
